# Drone configuration file
---
branches: [ master ]

clone:
  git:
    image: plugins/git:next
    pull: true

slack: &slack
  image: plugins/slack
  webhook: "${SLACK_WEBHOOK}"
  secrets: [ slack_webhook ]
  username: Drone CI
  icon_url: https://pbs.twimg.com/profile_images/573911705505259520/rShq67tG_400x400.png

steps:
  restore-cache:
    image: drillster/drone-volume-cache
    mount:
      - local-m2
    restore: true
    volumes:
      - "/tmp/cache:/cache"

  test:
    image: gowerstreet/forecast-build-image:1.2.3
    commands:
      - "CI_M2_REPO_PATH=local-m2 lein test"

  deploy:
    image: gowerstreet/forecast-build-image:1.2.3
    commands:
      - "CI_M2_REPO_PATH=local-m2 lein set-version 0.1.3.${CI_PIPELINE_NUMBER}"
      - "CI_M2_REPO_PATH=local-m2 lein deploy releases"
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  rebuild-cache:
    image: drillster/drone-volume-cache
    mount:
      - local-m2
    rebuild: true
    volumes:
      - "/tmp/cache:/cache"

  slack-pr-fail:
    <<: *slack
    channel: dev
    template: >
      *{{ build.status }}*
      <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}>
      (<https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|PR #{{ build.pull }}>)
      by {{ build.author }}
    when:
      event: pull_request
      status: failure

  slack-master-fail:
    <<: *slack
    channel: dev
    when:
      event: push
      branch: master
      status: failure
